version: '3.8'

services:
  mqtt-temperature-monitor-subscriber:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped
    network_mode: host

networks:
  default:
    driver: bridge